#!/usr/bin/env python3
"""Emit a self-contained ChimeraX .cxc that renders the k-means state gallery —
every state map tiled, fair-colored by golden-angle hue, soft-lit — as a still
and (optionally) a turntable movie. B-roll for the demo's Gate-3 scene.

Fair-coloring rule (opus-et-visualize/SKILL.md): color each candidate map
*distinctly*, never highlight a subset. Golden-angle hue spacing gives good
neighbour contrast: h=(i*0.618)%1, s=0.68, v=0.88. And `tile` RESETS lighting,
so `lighting soft` is emitted AFTER `tile`.

Usage:
  gen_gallery_cxc.py --maps-dir opuset/ribo/z8_expanded/analyze.35/kmeans20 \
      --out gallery.cxc [--pattern 'vol_*.mrc'] [--level 1.0] [--columns 5] \
      [--still ribo_state_gallery_3d.png] [--movie gallery.mp4]
  chimerax gallery.cxc          # GUI mode (reliable); --offscreen headless often fails (OSMesa/GL)
"""
import argparse
import colorsys
import re
from pathlib import Path


def _numkey(path):
    """Sort key by the last integer in the filename (reference0..19 -> 0..19,
    not the string order 0,1,10,11,...); falls back to the name."""
    nums = re.findall(r"\d+", Path(path).name)
    return (int(nums[-1]) if nums else 0, path)


def golden_hex(i):
    """i-th golden-angle color as #rrggbb (HSV h=(i*0.618)%1, s=0.68, v=0.88)."""
    h = (i * 0.618) % 1.0
    r, g, b = colorsys.hsv_to_rgb(h, 0.68, 0.88)
    return "#{:02x}{:02x}{:02x}".format(round(r * 255), round(g * 255), round(b * 255))


def percentile_level(map_path, pct):
    """The `pct`-th percentile of a map's voxel values — a fair, scale-independent
    contour (e.g. 98 shows the strongest 2% of density). Reads lazily via mrcfile."""
    import mrcfile
    import numpy as np
    with mrcfile.open(map_path, permissive=True) as f:
        return float(np.percentile(np.asarray(f.data, np.float32), pct))


def build_cxc(maps, out_cxc, level=None, percentile=None, columns=5, still=None,
              movie=None):
    lines = ["# Auto-generated by gen_gallery_cxc.py — k-means state gallery",
             "set bgColor white"]
    for m in maps:
        lines.append(f"open {m}")
    n = len(maps)
    lines.append("volume all style surface")
    if percentile is not None:
        # per-map contour at the given percentile — fair across maps whose value
        # scales differ; high percentile (98) suppresses the low-density speckle
        # that ChimeraX's auto level renders on high-resolution maps.
        for i, m in enumerate(maps):
            lines.append(f"volume #{i + 1} level {percentile_level(m, percentile):.5g}")
    elif level is not None:
        lines.append(f"volume all level {level}")
    for i in range(n):
        # ChimeraX numbers opened models #1..#n in open order
        lines.append(f"color #{i + 1} {golden_hex(i)}")
    lines.append(f"tile columns {columns}")
    lines.append("lighting soft")   # MUST come after `tile`
    lines.append("view")
    if still:
        lines.append(f"save {still} width 2000 height 1400 supersample 3")
    if movie:
        lines.append("movie record size 1600,900 supersample 3")
        lines.append(f"turn y 1 360 models #1-{n}")
        lines.append("wait 360")
        lines.append(f"movie encode {movie} framerate 30 quality high")
    Path(out_cxc).write_text("\n".join(lines) + "\n")
    return n


def main():
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--maps-dir", required=True, help="dir with the k-means state maps")
    ap.add_argument("--pattern", default="*.mrc", help="glob for the state maps")
    ap.add_argument("--out", required=True, help="output .cxc path")
    ap.add_argument("--level", type=float, default=None,
                    help="common surface contour level (default: ChimeraX auto per map — "
                         "set a value if the auto thresholds look uneven)")
    ap.add_argument("--percentile", type=float, default=None,
                    help="per-map contour at this percentile of voxel values "
                         "(e.g. 98). Fair across maps with different scales; "
                         "suppresses low-density speckle on high-res maps. "
                         "Overrides --level. Needs mrcfile+numpy.")
    ap.add_argument("--columns", type=int, default=5)
    ap.add_argument("--still", default=None, help="also save a still PNG")
    ap.add_argument("--movie", default=None, help="also record a turntable MP4")
    args = ap.parse_args()

    maps = sorted((str(p) for p in Path(args.maps_dir).glob(args.pattern)), key=_numkey)
    if not maps:
        raise SystemExit(f"no maps matching {args.pattern!r} in {args.maps_dir}")
    n = build_cxc(maps, args.out, level=args.level, percentile=args.percentile,
                  columns=args.columns, still=args.still, movie=args.movie)
    print(f"wrote {args.out} ({n} maps, {args.columns} columns)")
    print(f"render: chimerax {args.out}   (GUI mode — reliable; --offscreen headless often fails)")


if __name__ == "__main__":
    main()
